### ISSUE TITLE
Compiling ressources with webpack

### ISSUE THREAD

**Issue by spatiefr** [TypiCMS/Base#184]
This happend on a fresh successful install, runing command npm run dev
I didn't add any dependency 
**node v 15.0.9
npm v 7.6.3**

`ERROR in ./resources/scss/admin.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Undefined variable.
    ╷
116 │     @include transition($form-switch-transition);
    │                         ^^^^^^^^^^^^^^^^^^^^^^^
    ╵
  node_modules/bootstrap/scss/forms/_form-check.scss 116:25  @import
  node_modules/bootstrap/scss/_forms.scss 5:9                @import
  resources/scss/admin/_bootstrap.scss 23:9                  @import
  resources/scss/admin.scss 1:9                              root stylesheet
    at processResult (/pathtohome/aafcmsApp/node_modules/webpack/lib/NormalModule.js:598:19)
    at /pathtohome/aafcmsApp/node_modules/webpack/lib/NormalModule.js:692:5
    at /pathtohome/aafcmsApp/node_modules/loader-runner/lib/LoaderRunner.js:399:11
    at /pathtohome/aafcmsApp/node_modules/loader-runner/lib/LoaderRunner.js:251:18
    at context.callback (/pathtohome/aafcmsApp/node_modules/loader-runner/lib/LoaderRunner.js:124:13)
    at /pathtohome/aafcmsApp/node_modules/sass-loader/dist/index.js:54:7
    at Function.call$2 (/pathtohome/aafcmsApp/node_modules/sass/sass.dart.js:91729:16)
    at _render_closure1.call$2 (/pathtohome/aafcmsApp/node_modules/sass/sass.dart.js:80373:12)
    at _RootZone.runBinary$3$3 (/pathtohome/aafcmsApp/node_modules/sass/sass.dart.js:27269:18)
    at _FutureListener.handleError$1 (/pathtohome/aafcmsApp/node_modules/sass/sass.dart.js:25797:19)
    at _Future__propagateToListeners_handleError.call$0 (/pathtohome/aafcmsApp/node_modules/sass/sass.dart.js:26094:49)
    at Object._Future__propagateToListeners (/pathtohome/aafcmsApp/node_modules/sass/sass.dart.js:4543:77)
    at _Future._completeError$2 (/pathtohome/aafcmsApp/node_modules/sass/sass.dart.js:25927:9)
    at _AsyncAwaitCompleter.completeError$2 (/pathtohome/aafcmsApp/node_modules/sass/sass.dart.js:25270:12)
    at Object._asyncRethrow (/pathtohome/aafcmsApp/node_modules/sass/sass.dart.js:4292:17)
    at /pathtohome/aafcmsApp/node_modules/sass/sass.dart.js:13233:20

ERROR in ./resources/scss/public.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Undefined variable.
    ╷
116 │     @include transition($form-switch-transition);
    │                         ^^^^^^^^^^^^^^^^^^^^^^^
    ╵
  node_modules/bootstrap/scss/forms/_form-check.scss 116:25  @import
  node_modules/bootstrap/scss/_forms.scss 5:9                @import
  resources/scss/public/_bootstrap.scss 23:9                 @import
  resources/scss/public.scss 1:9                             root stylesheet
    at processResult (/pathtohome/aafcmsApp/node_modules/webpack/lib/NormalModule.js:598:19)
    at /pathtohome/aafcmsApp/node_modules/webpack/lib/NormalModule.js:692:5
    at /pathtohome/aafcmsApp/node_modules/loader-runner/lib/LoaderRunner.js:399:11
    at /pathtohome/aafcmsApp/node_modules/loader-runner/lib/LoaderRunner.js:251:18
    at context.callback (/pathtohome/aafcmsApp/node_modules/loader-runner/lib/LoaderRunner.js:124:13)
    at /pathtohome/aafcmsApp/node_modules/sass-loader/dist/index.js:54:7
    at Function.call$2 (/pathtohome/aafcmsApp/node_modules/sass/sass.dart.js:91729:16)
    at _render_closure1.call$2 (/pathtohome/aafcmsApp/node_modules/sass/sass.dart.js:80373:12)
    at _RootZone.runBinary$3$3 (/pathtohome/aafcmsApp/node_modules/sass/sass.dart.js:27269:18)
    at _FutureListener.handleError$1 (/pathtohome/aafcmsApp/node_modules/sass/sass.dart.js:25797:19)
    at _Future__propagateToListeners_handleError.call$0 (/pathtohome/aafcmsApp/node_modules/sass/sass.dart.js:26094:49)
    at Object._Future__propagateToListeners (/pathtohome/aafcmsApp/node_modules/sass/sass.dart.js:4543:77)
    at _Future._completeError$2 (/pathtohome/aafcmsApp/node_modules/sass/sass.dart.js:25927:9)
    at _AsyncAwaitCompleter.completeError$2 (/pathtohome/aafcmsApp/node_modules/sass/sass.dart.js:25270:12)
    at Object._asyncRethrow (/pathtohome/aafcmsApp/node_modules/sass/sass.dart.js:4292:17)
    at /pathtohome/aafcmsApp/node_modules/sass/sass.dart.js:13233:20

2 ERRORS in child compilations (Use 'stats.children: true' resp. '--stats-children' for more details)
webpack compiled with 4 errors
npm ERR! code 1
npm ERR! path /pathtohome/aafcmsApp
npm ERR! command failed
npm ERR! command sh -c mix

npm ERR! A complete log of this run can be found in:
npm ERR!     /pathtohome/.npm/_logs/2021-03-17T13_10_51_114Z-debug.log
`

**Comment by sdebacker** [comment]
This should be fixed now.
