### ISSUE TITLE
CamelCase  typicms:create errors

### ISSUE THREAD

**Issue by eahrold** [TypiCMS/Base#45]
So I found an interesting edge case.

if I do `artisan typicms:create Tagcollection` everything works fine

However if I do `artisan typicms:create TagCollection ` with a camel case I get this in the admin portal

Looks like a case sensitive fs issue, in the vein of this https://laracasts.com/discuss/channels/general-discussion/homestead-and-case-sensitivity

_(Or is it splitting on the second capital letter and inserting an underscore?)_

```
Next ErrorException: No hint path defined for [tag_collections]. (View: /home/vagrant/Code/MyCatsProject/resources/views/vendor/core/admin/index.blade.php) in /home/vagrant/Code/MyCatsProject/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php:112
Stack trace:
#0 /home/vagrant/Code/MyCatsProject/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(44): Illuminate\View\Engines\CompilerEngine->handleViewException(Object(InvalidArgumentException), 1)
#1 /home/vagrant/Code/MyCatsProject/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(59): Illuminate\View\Engines\PhpEngine->evaluatePath('/home/vagrant/C...', Array)
#2 /home/vagrant/Code/MyCatsProject/vendor/laravel/framework/src/Illuminate/View/View.php(147): Illuminate\View\Engines\CompilerEngine->get('/home/vagrant/C...', Array)
#3 /home/vagrant/Code/MyCatsProject/vendor/laravel/framework/src/Illuminate/View/View.php(118): Illuminate\View\View->getContents()
#4 /home/vagrant/Code/MyCatsProject/vendor/laravel/framework/src/Illuminate/View/View.php(83): Illuminate\View\View->renderContents()
#5 /home/vagrant/Code/MyCatsProject/vendor/laravel/framework/src/Illuminate/Http/Response.php(53): Illuminate\View\View->render()
#6 /home/vagrant/Code/MyCatsProject/vendor/symfony/http-foundation/Response.php(197): Illuminate\Http\Response->setContent(Object(Illuminate\View\View))
#7 /home/vagrant/Code/MyCatsProject/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1030): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\View\View))
#8 /home/vagrant/Code/MyCatsProject/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(94): Illuminate\Routing\Router->prepareResponse(Object(Illuminate\Http\Request), Object(Illuminate\View\View))
#9 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#10 /home/vagrant/Code/MyCatsProject/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#11 /home/vagrant/Code/MyCatsProject/vendor/typicms/core/src/Http/Middleware/UserPrefs.php(26): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#12 [internal function]: TypiCMS\Modules\Core\Http\Middleware\UserPrefs->handle(Object(Illuminate\Http\Request), Object(Closure))
#13 /home/vagrant/Code/MyCatsProject/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#14 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#15 /home/vagrant/Code/MyCatsProject/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#16 /home/vagrant/Code/MyCatsProject/vendor/typicms/core/src/Http/Middleware/JavaScriptData.php(39): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#17 [internal function]: TypiCMS\Modules\Core\Http\Middleware\JavaScriptData->handle(Object(Illuminate\Http\Request), Object(Closure))
#18 /home/vagrant/Code/MyCatsProject/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#19 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#20 /home/vagrant/Code/MyCatsProject/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#21 /home/vagrant/Code/MyCatsProject/vendor/typicms/core/src/Http/Middleware/AdminLocale.php(38): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#22 [internal function]: TypiCMS\Modules\Core\Http\Middleware\AdminLocale->handle(Object(Illuminate\Http\Request), Object(Closure))
#23 /home/vagrant/Code/MyCatsProject/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#24 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#25 /home/vagrant/Code/MyCatsProject/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#26 /home/vagrant/Code/MyCatsProject/vendor/typicms/core/src/Http/Middleware/Authorization.php(27): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#27 [internal function]: TypiCMS\Modules\Core\Http\Middleware\Authorization->handle(Object(Illuminate\Http\Request), Object(Closure))
#28 /home/vagrant/Code/MyCatsProject/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#29 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#30 /home/vagrant/Code/MyCatsProject/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#31 /home/vagrant/Code/MyCatsProject/app/Http/Middleware/Authenticate.php(28): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#32 [internal function]: App\Http\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure))
#33 /home/vagrant/Code/MyCatsProject/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#34 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#35 /home/vagrant/Code/MyCatsProject/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#36 /home/vagrant/Code/MyCatsProject/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(64): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#37 [internal function]: Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#38 /home/vagrant/Code/MyCatsProject/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#39 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#40 /home/vagrant/Code/MyCatsProject/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#41 /home/vagrant/Code/MyCatsProject/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#42 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#43 /home/vagrant/Code/MyCatsProject/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#44 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#45 /home/vagrant/Code/MyCatsProject/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#46 /home/vagrant/Code/MyCatsProject/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#47 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#48 /home/vagrant/Code/MyCatsProject/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#49 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#50 /home/vagrant/Code/MyCatsProject/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#51 /home/vagrant/Code/MyCatsProject/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#52 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#53 /home/vagrant/Code/MyCatsProject/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#54 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#55 /home/vagrant/Code/MyCatsProject/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#56 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#57 /home/vagrant/Code/MyCatsProject/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#58 /home/vagrant/Code/MyCatsProject/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(96): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#59 /home/vagrant/Code/MyCatsProject/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(54): Illuminate\Routing\ControllerDispatcher->callWithinStack(Object(TypiCMS\Modules\TagCollections\Http\Controllers\AdminController), Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'index')
#60 /home/vagrant/Code/MyCatsProject/vendor/laravel/framework/src/Illuminate/Routing/Route.php(174): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'TypiCMS\\Modules...', 'index')
#61 /home/vagrant/Code/MyCatsProject/vendor/laravel/framework/src/Illuminate/Routing/Route.php(140): Illuminate\Routing\Route->runController(Object(Illuminate\Http\Request))
#62 /home/vagrant/Code/MyCatsProject/vendor/laravel/framework/src/Illuminate/Routing/Router.php(703): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#63 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#64 /home/vagrant/Code/MyCatsProject/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#65 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#66 /home/vagrant/Code/MyCatsProject/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#67 /home/vagrant/Code/MyCatsProject/vendor/laravel/framework/src/Illuminate/Routing/Router.php(705): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#68 /home/vagrant/Code/MyCatsProject/vendor/laravel/framework/src/Illuminate/Routing/Router.php(678): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#69 /home/vagrant/Code/MyCatsProject/vendor/laravel/framework/src/Illuminate/Routing/Router.php(654): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#70 /home/vagrant/Code/MyCatsProject/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(246): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#71 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#72 /home/vagrant/Code/MyCatsProject/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#73 /home/vagrant/Code/MyCatsProject/vendor/barryvdh/laravel-debugbar/src/Middleware/Debugbar.php(49): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#74 [internal function]: Barryvdh\Debugbar\Middleware\Debugbar->handle(Object(Illuminate\Http\Request), Object(Closure))
#75 /home/vagrant/Code/MyCatsProject/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#76 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#77 /home/vagrant/Code/MyCatsProject/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#78 /home/vagrant/Code/MyCatsProject/vendor/edvinaskrucas/notification/src/Krucas/Notification/Middleware/NotificationMiddleware.php(58): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#79 [internal function]: Krucas\Notification\Middleware\NotificationMiddleware->handle(Object(Illuminate\Http\Request), Object(Closure))
#80 /home/vagrant/Code/MyCatsProject/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#81 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#82 /home/vagrant/Code/MyCatsProject/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#83 /home/vagrant/Code/MyCatsProject/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(44): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#84 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#85 /home/vagrant/Code/MyCatsProject/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#86 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#87 /home/vagrant/Code/MyCatsProject/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#88 /home/vagrant/Code/MyCatsProject/vendor/typicms/core/src/Http/Middleware/PublicLocale.php(50): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#89 [internal function]: TypiCMS\Modules\Core\Http\Middleware\PublicLocale->handle(Object(Illuminate\Http\Request), Object(Closure))
#90 /home/vagrant/Code/MyCatsProject/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#91 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#92 /home/vagrant/Code/MyCatsProject/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#93 /home/vagrant/Code/MyCatsProject/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(62): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#94 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#95 /home/vagrant/Code/MyCatsProject/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#96 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#97 /home/vagrant/Code/MyCatsProject/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#98 /home/vagrant/Code/MyCatsProject/vendor/dingo/api/src/Http/Middleware/Request.php(95): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#99 [internal function]: Dingo\Api\Http\Middleware\Request->handle(Object(Illuminate\Http\Request), Object(Closure))
#100 /home/vagrant/Code/MyCatsProject/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#101 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#102 /home/vagrant/Code/MyCatsProject/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#103 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#104 /home/vagrant/Code/MyCatsProject/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#105 /home/vagrant/Code/MyCatsProject/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(132): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#106 /home/vagrant/Code/MyCatsProject/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(99): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#107 /home/vagrant/Code/MyCatsProject/public/index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#108 {main}  
```

**Comment by sdebacker** [comment]
Nice, I will investigate more on this soon.

**Comment by sdebacker** [comment]
This commit corrected the bug: https://github.com/TypiCMS/Core/commit/128b452a03aa47f5f92e44c4403c59ce46e7a14a

Thank you for the bug report.

**Comment by eahrold** [comment]
Awesome. And thanks, I'm really enjoying working with TypiCMS.
