### ISSUE TITLE
Admin backend on all versions of IE broken

### ISSUE THREAD

**Issue by eahrold** [TypiCMS/Base#52]
Not sure if you can reproduce, but for me the admin backend is breaking with all versions if IE (9-Edge)
I've tested this on an existing project, and a fresh installation of typicms

The site works correct on Chrome, Safari, and Firefox

Here's the error I'm seeing 
```
TypeError: Object doesn't support this action
   at Anonymous function (http://pretendco.com/js/admin/components.min.js:13:22704)
   at i (http://pretendco.com/js/admin/components.min.js:4:21865)
   at Anonymous function (http://pretendco.com/js/admin/components.min.js:4:20272)
   at i (http://pretendco.com/js/admin/components.min.js:4:21865)
   at Anonymous function (http://pretendco.com/js/admin/components.min.js:4:22458)
   at r (http://pretendco.com/js/admin/components.min.js:4:21488)
   at i (http://pretendco.com/js/admin/components.min.js:4:21822)
   at Anonymous function (http://pretendco.com/js/admin/components.min.js:5:11916)
   at m (http://pretendco.com/js/admin/components.min.js:5:1481)
   at s (http://pretendco.com/js/admin/components.min.js:4:30008)
```

And After unminifying components.js
```
TypeError: Object doesn't support this action
   at Anonymous function (http://pretendco.com/js/admin/components.min.js:52609:9)
   at invoke (http://pretendco.com/js/admin/components.min.js:15631:9)
   at enforcedReturnValue (http://pretendco.com/js/admin/components.min.js:15470:7)
   at invoke (http://pretendco.com/js/admin/components.min.js:15631:9)
   at Anonymous function (http://pretendco.com/js/admin/components.min.js:15430:13)
   at getService (http://pretendco.com/js/admin/components.min.js:15577:11)
   at injectionArgs (http://pretendco.com/js/admin/components.min.js:15600:9)
   at invoke (http://pretendco.com/js/admin/components.min.js:15623:7)
   at Anonymous function (http://pretendco.com/js/admin/components.min.js:20882:11)
   at nodeLinkFn (http://pretendco.com/js/admin/components.min.js:19954:11)
```

And the Screen shot

<img width="1238" alt="screen shot 2016-03-23 at 10 15 34 pm" src="https://cloud.githubusercontent.com/assets/3740088/14007456/e149d19a-f144-11e5-8f35-8e0d4b687a80.png">

_Note: The news model here has a couple hundred entries that are not appearing_
Any advice would be much appericaited.

**Comment by eahrold** [comment]
Update,
Got to the root of it.
Seems like IE `new URL(window.location)` was the problem in this bit
```javascript
  // Creating an 'update' method (PUT)
    angular.module('typicms').factory('$api', ['$resource', function ($resource) {

        var url = new URL(window.location),
            path = url.pathname,
            moduleName = path.split('/')[2];
```
Changing to this 
```javascript
    	// IE chceck based on
    	// https://msdn.microsoft.com/en-us/library/ms537509(v=vs.85).aspx
    	if (navigator.appName == 'Microsoft Internet Explorer'){
    		var loc = window.location
    	} else {
    		var loc = new URL(window.location)
    	}

        var url = loc,
            path = url.pathname,
            moduleName = path.split('/')[2];
```
Seems to have fixed the problem for IE.

**Comment by sdebacker** [comment]
Ok, I wasn't aware that URL() in JS was an experimental technology.
I will simply use window.location

**Comment by sdebacker** [comment]
Thank you for the bug report.
