### ISSUE TITLE
How to install / enable additional modules?

### ISSUE THREAD

**Issue by londoh** [TypiCMS/Base#7]
Hi,

I just tried an install of the 2.0/L5 series

I got similar mysql issue as reported by others in closed issue #3 
But install does proceed after a manual setup of env file

However installation then appears to be short of a lot of modules, such as:
Categories, Projects, News, Events, Places, Partners

These will install with a manual inclusion in composer
but then no migration, or dashboard views etc

Is this something that is coming?

Regards

l.

**Comment by sdebacker** [comment]
Here is how to install the news module:

1. Run ```composer require typicms/news```
2. Add ```TypiCMS\Modules\News\Providers\ModuleProvider``` to **config/app.php**,
3. Run ```php artisan vendor:publish```
4. Run ```php artisan migrate```

**Comment by londoh** [comment]
thanks for reply
ah yea ok, - the serviceproviders
almost works, but now routes are 404 on all newly installed modules (Categories, Projects, News etc)
route.list shows routes are there.
all modules show same error:
```
exception 'Illuminate\Database\Eloquent\ModelNotFoundException' with message 'No query results for model [TypiCMS\Modules\Pages\Models\Page]
```
always Page

heres the stack trace:

```
[2015-04-12 17:54:06] local.ERROR: exception 'Illuminate\Database\Eloquent\ModelNotFoundException' with message 'No query results for model [TypiCMS\Modules\Pages\Models\Page].' in /home/londoh/Development/www/l5typi/laravel/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php:151
Stack trace:
#0 /home/londoh/Development/www/l5typi/laravel/vendor/typicms/pages/src/Repositories/EloquentPage.php(59): Illuminate\Database\Eloquent\Builder->firstOrFail()
#1 /home/londoh/Development/www/l5typi/laravel/vendor/typicms/pages/src/Http/Controllers/PublicController.php(45): TypiCMS\Modules\Pages\Repositories\EloquentPage->getFirstByUri('admin/news')
#2 [internal function]: TypiCMS\Modules\Pages\Http\Controllers\PublicController->uri('admin/news')
#3 /home/londoh/Development/www/l5typi/laravel/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(246): call_user_func_array(Array, Array)
#4 /home/londoh/Development/www/l5typi/laravel/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(162): Illuminate\Routing\Controller->callAction('uri', Array)
#5 /home/londoh/Development/www/l5typi/laravel/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(107): Illuminate\Routing\ControllerDispatcher->call(Object(TypiCMS\Modules\Pages\Http\Controllers\PublicController), Object(Illuminate\Routing\Route), 'uri')
#6 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#7 /home/londoh/Development/www/l5typi/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#8 /home/londoh/Development/www/l5typi/laravel/vendor/typicms/core/src/Http/Middleware/PublicLocale.php(42): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#9 /home/londoh/Development/www/l5typi/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(125): TypiCMS\Http\Middleware\PublicLocale->handle(Object(Illuminate\Http\Request), Object(Closure))
#10 /home/londoh/Development/www/l5typi/laravel/vendor/typicms/core/src/Http/Middleware/PublicAccess.php(28): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#11 /home/londoh/Development/www/l5typi/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(125): TypiCMS\Http\Middleware\PublicAccess->handle(Object(Illuminate\Http\Request), Object(Closure))
#12 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#13 /home/londoh/Development/www/l5typi/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(101): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#14 /home/londoh/Development/www/l5typi/laravel/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(108): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#15 /home/londoh/Development/www/l5typi/laravel/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(67): Illuminate\Routing\ControllerDispatcher->callWithinStack(Object(TypiCMS\Modules\Pages\Http\Controllers\PublicController), Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'uri')
#16 /home/londoh/Development/www/l5typi/laravel/vendor/laravel/framework/src/Illuminate/Routing/Route.php(198): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'TypiCMS\\Modules...', 'uri')
#17 /home/londoh/Development/www/l5typi/laravel/vendor/laravel/framework/src/Illuminate/Routing/Route.php(131): Illuminate\Routing\Route->runWithCustomDispatcher(Object(Illuminate\Http\Request))
#18 /home/londoh/Development/www/l5typi/laravel/vendor/laravel/framework/src/Illuminate/Routing/Router.php(692): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#19 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#20 /home/londoh/Development/www/l5typi/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#21 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#22 /home/londoh/Development/www/l5typi/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(101): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#23 /home/londoh/Development/www/l5typi/laravel/vendor/laravel/framework/src/Illuminate/Routing/Router.php(694): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#24 /home/londoh/Development/www/l5typi/laravel/vendor/laravel/framework/src/Illuminate/Routing/Router.php(661): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#25 /home/londoh/Development/www/l5typi/laravel/vendor/laravel/framework/src/Illuminate/Routing/Router.php(619): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#26 /home/londoh/Development/www/l5typi/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(214): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#27 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#28 /home/londoh/Development/www/l5typi/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#29 /home/londoh/Development/www/l5typi/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(43): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#30 /home/londoh/Development/www/l5typi/laravel/app/Http/Middleware/VerifyCsrfToken.php(17): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#31 /home/londoh/Development/www/l5typi/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(125): App\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#32 /home/londoh/Development/www/l5typi/laravel/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(55): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#33 /home/londoh/Development/www/l5typi/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(125): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#34 /home/londoh/Development/www/l5typi/laravel/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(61): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#35 /home/londoh/Development/www/l5typi/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(125): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#36 /home/londoh/Development/www/l5typi/laravel/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(36): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#37 /home/londoh/Development/www/l5typi/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(125): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#38 /home/londoh/Development/www/l5typi/laravel/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(40): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#39 /home/londoh/Development/www/l5typi/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(125): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#40 /home/londoh/Development/www/l5typi/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(42): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#41 /home/londoh/Development/www/l5typi/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(125): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#42 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#43 /home/londoh/Development/www/l5typi/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(101): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#44 /home/londoh/Development/www/l5typi/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(115): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#45 /home/londoh/Development/www/l5typi/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(84): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#46 /home/londoh/Development/www/l5typi/laravel/public/index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#47 {main}  
```

**Comment by sdebacker** [comment]
I forgot to mention that modules services provider must be ```beforeTypiCMS\Providers\CoreServiceProvider``` in config/app.php

**Comment by sdebacker** [comment]
I’ve updated the readme with steps to install a module.

**Comment by rccasas** [comment]
I think it's not really closed.

I've tried several modules and it seems the modules are using a different approach to registering routes than Pages module.

For example, news module uses 

$routes = $this->app->make('TypiCMS.routes');

After that, $routes var is empty, so routes for the module are not created.

The routes for pages are created using:

$app->make('TypiCMS\Modules\Pages\Repositories\PageInterface')->getForRoutes();

which returns the routes for all pages and it adds them to the routing system.

The loading order of providers is the same you wrote.

**Comment by sdebacker** [comment]
Yes. If you want public routes for News, you have to create a page linked to news module. The page uri will then be the news list.

**Comment by sdebacker** [comment]
Does it work for you ?

**Comment by rccasas** [comment]
It works fine! Thanks a lot. I didn't know the function of that module dropdown in a page.
